version: '3.7'
services:

  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: 626452
      POSTGRES_USER: book
      POSTGRES_DB: book
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U bot" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db-data-bot-postgres:/var/lib/postgresql/data

  web:
    build: ./backend
    restart: always
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: books
    volumes:
      - .:/books
    environment:
      DB_HOST: db
      DB_NAME: book
      DB_USER: book
      DB_PASSWORD: 626452
    ports:
      - "8000:8000"
    depends_on:
      - db
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"

  front:
    build: ./frontend/books
    restart: unless-stopped
    ports:
      - '8080:8080'
    command: npm run serve


volumes:
  db-data-bot-postgres:
